name: Run Cloud Custodian
description: Run Cloud Custodian

inputs:
  configPath:
    description: 'Path to the Cloud Custodian policy file'
    required: true

  preview:
    description: 'Run Cloud Custodian in preview mode'
    required: false
    default: false

runs:
  using: composite
  steps:

    - name: Install Cloud Custodian
      shell: bash
      run: |
        pip install c7n c7n_azure > /dev/null
        pip install -U pyopenssl > /dev/null


    - name: Run Cloud Custodian
      shell: bash
      run: |
        DRYRUN_FLAG=""
        if [ "${{ inputs.preview }}" = "true" ]; then
          DRYRUN_FLAG="--dryrun"
        fi
        custodian run -s . $DRYRUN_FLAG ${{ inputs.configPath }}
