name: Run Cloud Custodian
description: Run Cloud Custodian

inputs:
  configPath:
    description: 'Path to the Cloud Custodian policy file'
    required: true

  preview:
    description: 'Run Cloud Custodian in preview mode'
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Display parameters
      shell: bash
      run: |
        echo ${{ inputs.configPath }}
