name: Run Cloud Custodian
description: Run Cloud Custodian

inputs:
  configPath:
    description: 'Path to the Cloud Custodian policy file'
    required: true

  preview:
    description: 'Run Cloud Custodian in preview mode'
    required: false
    default: false

runs:
  using: composite
  steps:

    - name: Install Cloud Custodian
      shell: bash
      run: pip install c7n c7n_azure

    - name: Run Cloud Custodian
      shell: bash
      run: |
        custodian
