name: Run Cloud Custodian
description: Run Cloud Custodian

inputs:
  configPath:
    description: 'Path to the Cloud Custodian policy file'
    required: true

  preview:
    description: 'Run Cloud Custodian in preview mode'
    required: false
    default: false

runs:
  using: composite
  steps:

    - name: Install Cloud Custodian
      shell: bash
      run: docker pull cloudcustodian/c7n

    - name: Run Cloud Custodian
      shell: bash
      run: |
        docker run -i 
          -v ${{ inputs.configPath }}:/home/custodian/policy.yml
          --env-file <(env | grep "^AWS\|^AZURE\|^GOOGLE")
            cloudcustodian/c7n run -v -s . /home/custodian/policy.yml
