policies:
  - name: remove-lab
    description: |
      Removes lab resources from subscription
    resource: azure.armresource
    filters:
      - tag:group: present
      # - type: value
      #   key: tags.group
      #   value: lab
    actions:
      - type: delete
