name: Cleanup lab environments

on:
  schedule:
  # Runs at midnight New Zealand time
  - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      preview:
        description: Preview changes
        type: choice
        required: true
        options:
          - false
          - true

permissions:
  id-token: write
  contents: read

env:
  azureLabCleanupPath: ${{ github.workspace }}/config/azure-lab.yml
  previewMode: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preview || false }}

jobs:
  azure-cleanup:
    name: azure-cleanup
    runs-on: ubuntu-latest
    environment: Azure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Clean Azure lab
        uses: ./.github/actions/cloud-custodian
        with:
          configPath: ${{ env.azureLabCleanupPath }}
          preview: ${{ env.previewMode }}